// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         string `gorm:"column:id;type:varchar(512);primaryKey" json:"id"`  // id
	Name       string `gorm:"column:name;type:varchar(255)" json:"name"`         // 名称
	Phone      string `gorm:"column:phone;type:varchar(255)" json:"phone"`       // 手机号
	Password   string `gorm:"column:password;type:varchar(255)" json:"password"` // 密码
	Image      string `gorm:"column:image;type:varchar(255)" json:"image"`       // 头像
	CreateTime int64  `gorm:"column:create_time;type:bigint" json:"create_time"` // 创建时间
	UpdateTime int64  `gorm:"column:update_time;type:bigint" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
